// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsStg {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2SAeu6g34FMzdKmeZ8Pd8goaE3jxvAtg',
    appId: '1:412909355967:web:5892843364ed559e7d970a',
    messagingSenderId: '412909355967',
    projectId: 'health-mn-staging',
    authDomain: 'health-mn-staging.firebaseapp.com',
    storageBucket: 'health-mn-staging.firebasestorage.app',
    measurementId: 'G-XM0D6C6ZHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSEfST66K3mlkWQ8M7Trvg73h7_xVAhEI',
    appId: '1:412909355967:android:08f8eb629e52b4957d970a',
    messagingSenderId: '412909355967',
    projectId: 'health-mn-staging',
    storageBucket: 'health-mn-staging.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2SAeu6g34FMzdKmeZ8Pd8goaE3jxvAtg',
    appId: '1:412909355967:web:7d55220b85af030e7d970a',
    messagingSenderId: '412909355967',
    projectId: 'health-mn-staging',
    authDomain: 'health-mn-staging.firebaseapp.com',
    storageBucket: 'health-mn-staging.firebasestorage.app',
    measurementId: 'G-Q62Q1NL68V',
  );
}
