// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYmmbjXa-cdxDI6Zsl0uSLwJJK2hSt8u4',
    appId: '1:266512718933:web:8528709e06d90e011b88dc',
    messagingSenderId: '266512718933',
    projectId: 'health-mn-prod',
    authDomain: 'health-mn-prod.firebaseapp.com',
    storageBucket: 'health-mn-prod.firebasestorage.app',
    measurementId: 'G-6P43QPZ423',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrj8P1C7YclP_Shkz_PG6rEGCkLEojJC0',
    appId: '1:266512718933:android:f9491b2b8b2debe21b88dc',
    messagingSenderId: '266512718933',
    projectId: 'health-mn-prod',
    storageBucket: 'health-mn-prod.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYmmbjXa-cdxDI6Zsl0uSLwJJK2hSt8u4',
    appId: '1:266512718933:web:55ea20a53b0612011b88dc',
    messagingSenderId: '266512718933',
    projectId: 'health-mn-prod',
    authDomain: 'health-mn-prod.firebaseapp.com',
    storageBucket: 'health-mn-prod.firebasestorage.app',
    measurementId: 'G-LV88DWFMJD',
  );
}
