// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtON2PhaTtLSLDuawH7fNYDg7CPIyz2xo',
    appId: '1:155656307072:web:44151850d5793818044165',
    messagingSenderId: '155656307072',
    projectId: 'chat-app-5d601',
    authDomain: 'chat-app-5d601.firebaseapp.com',
    databaseURL: 'https://chat-app-5d601-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-5d601.appspot.com',
    measurementId: 'G-CSK1PJWHLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANr3MNTGaGfhfrPt6uohyp26gZQ-_ilcU',
    appId: '1:155656307072:android:a0eefb7abc3bb3eb044165',
    messagingSenderId: '155656307072',
    projectId: 'chat-app-5d601',
    databaseURL: 'https://chat-app-5d601-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-5d601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtlw4NN5Yv88V_CJtIp-GeWSBtTaMEURM',
    appId: '1:155656307072:ios:0341b1f2c827fd3b044165',
    messagingSenderId: '155656307072',
    projectId: 'chat-app-5d601',
    databaseURL: 'https://chat-app-5d601-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-5d601.appspot.com',
    iosBundleId: 'com.example.healthManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtlw4NN5Yv88V_CJtIp-GeWSBtTaMEURM',
    appId: '1:155656307072:ios:0341b1f2c827fd3b044165',
    messagingSenderId: '155656307072',
    projectId: 'chat-app-5d601',
    databaseURL: 'https://chat-app-5d601-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-5d601.appspot.com',
    iosBundleId: 'com.example.healthManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWdvvnEhW9O_6SpITtqZ7a4j_i4CtzOno',
    appId: '1:155656307072:web:6fd2179a46ddec7f044165',
    messagingSenderId: '155656307072',
    projectId: 'chat-app-5d601',
    authDomain: 'chat-app-5d601.firebaseapp.com',
    databaseURL: 'https://chat-app-5d601-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-5d601.appspot.com',
    measurementId: 'G-QLVHZ4RT1M',
  );

}